//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.arcanic.dk/", ConfigurationName="CourseSoap")]
public interface CourseSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/CourseCatalogVersions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> CourseCatalogVersionsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetKeyValuesByVolume", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetKeyValuesByVolumeAsync(string volume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCatalogVersionSelection", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCatalogVersionSelectionAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseByPassVolumeSettings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseByPassVolumeSettingsAsync(string courseCode, string yearGroup, System.Guid systemToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourse", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseAsync(string courseCode, string yearGroup);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseNewestPublic", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseNewestPublicAsync(string CourseCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseNewestBeforeVolume", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseNewestBeforeVolumeAsync(string CourseCode, string Volume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseResponsibleList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseResponsibleListAsync(string courseCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseTeachersList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseTeachersListAsync(string courseCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseTeachersAndSuperusersList", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseTeachersAndSuperusersListAsync(string courseCode, bool includeSuperUsers);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetLabels", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetLabelsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/SearchDtuShb_Full", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> SearchDtuShb_FullAsync(string courseCode, string searchWords, string department, string teachingPeriod, string CourseCatalogVersion, string courseCodeStart, string teachingLanguage, string courseIDList, string resultType, string education, string CourseType, string MasterRegular, string openUniversity, string textStudieboksen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/PublishedPicker", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CourseTitleAndVolume[]> PublishedPickerAsync(string term, string volume, int maxResults);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/DraftPicker", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CourseTitleAndVolume[]> DraftPickerAsync(string term, string volume, int maxResults, System.Guid systemToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/SearchDtuShbByCourseCodeOrTitle", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> SearchDtuShbByCourseCodeOrTitleAsync(string searchWords);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseFromCourseId", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseFromCourseIdAsync(int courseId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDepartments", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetStudieBoks", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetStudieBoksAsync(string aargang, string lang);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetHTMLDescription", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetHTMLDescriptionAsync(string CourseCode, string CourseCatalogVersion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetOpenCatalogVersions", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetOpenCatalogVersionsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetTimeTableGroup", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetTimeTableGroupAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDepartmentsGivenCatalog", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsGivenCatalogAsync(string CourseCatalogVersion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetSearchValues", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetSearchValuesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseCodeStartLetters", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseCodeStartLettersAsync(string catalogVersion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesByCourseCodeStartingLetters", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByCourseCodeStartingLettersAsync(string letters, string catalogversion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesByStartingLetter", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByStartingLetterAsync(char letter, string userLang, string catalogversion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesByDepartment", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByDepartmentAsync(string department, string catalogversion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesByProgrammeLevelInPreferedVolume", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByProgrammeLevelInPreferedVolumeAsync(string programmeLevel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetArchivedCoursesByVolumeAndDepartment", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetArchivedCoursesByVolumeAndDepartmentAsync(string volume, string department);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseHoldings", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseHoldingsAsync(string courseCode, string volume, string lang);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseHoldingsById", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseHoldingsByIdAsync(int courseId, string lang);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetFrontMessage", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetFrontMessageAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseResponsiblesCoursesInOpenVolumes", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseResponsiblesCoursesInOpenVolumesAsync(int cwis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetTeacherCoursesInCurrentAndPriorYear", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetTeacherCoursesInCurrentAndPriorYearAsync(int cwis);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourselistForExamReporting", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourselistForExamReportingAsync(string courseNumbers, string yearGroup, string departmentKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCourseResponsiblesCoursesInSpecificVolume", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseResponsiblesCoursesInSpecificVolumeAsync(int cwis, string volume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDepartmentsResourcesInSpecificVolume", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsResourcesInSpecificVolumeAsync(string volume);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDataForAUSReport", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForAUSReportAsync(string volume, string[] courseCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDataForStudyplan", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForStudyplanAsync(string volume, string[] courseCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesTitles", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CourseTitle[]> GetCoursesTitlesAsync(string volume, string[] courseCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDataForGradeEntry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForGradeEntryAsync(string volume, string[] courseCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDataForExamPlanner", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CourseExamPlanner[]> GetDataForExamPlannerAsync(string volume, string[] courseCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetTeachingHours", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<GetTeachingHoursResponse> GetTeachingHoursAsync(GetTeachingHoursRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetCoursesWithDuration", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<string[]> GetCoursesWithDurationAsync(string volume, string duration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.arcanic.dk/GetDataForEuroTeQ", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<System.Xml.XmlNode> GetDataForEuroTeQAsync(string yearGroup, System.Guid systemId);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arcanic.dk/")]
public partial class CourseTitleAndVolume
{
    
    private string courseCodeField;
    
    private string danishField;
    
    private string englishField;
    
    private string volumeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CourseCode
    {
        get
        {
            return this.courseCodeField;
        }
        set
        {
            this.courseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Danish
    {
        get
        {
            return this.danishField;
        }
        set
        {
            this.danishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string English
    {
        get
        {
            return this.englishField;
        }
        set
        {
            this.englishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Volume
    {
        get
        {
            return this.volumeField;
        }
        set
        {
            this.volumeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arcanic.dk/")]
public partial class CourseExamPlanner
{
    
    private string courseCodeField;
    
    private string assessmentKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CourseCode
    {
        get
        {
            return this.courseCodeField;
        }
        set
        {
            this.courseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string AssessmentKey
    {
        get
        {
            return this.assessmentKeyField;
        }
        set
        {
            this.assessmentKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arcanic.dk/")]
public partial class CourseTitle
{
    
    private string courseCodeField;
    
    private string danishTitleField;
    
    private string englishTitleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string CourseCode
    {
        get
        {
            return this.courseCodeField;
        }
        set
        {
            this.courseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DanishTitle
    {
        get
        {
            return this.danishTitleField;
        }
        set
        {
            this.danishTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string EnglishTitle
    {
        get
        {
            return this.englishTitleField;
        }
        set
        {
            this.englishTitleField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTeachingHours", WrapperNamespace="http://www.arcanic.dk/", IsWrapped=true)]
public partial class GetTeachingHoursRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.arcanic.dk/", Order=0)]
    public string volume;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.arcanic.dk/", Order=1)]
    public string courseCode;
    
    public GetTeachingHoursRequest()
    {
    }
    
    public GetTeachingHoursRequest(string volume, string courseCode)
    {
        this.volume = volume;
        this.courseCode = courseCode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetTeachingHoursResponse", WrapperNamespace="http://www.arcanic.dk/", IsWrapped=true)]
public partial class GetTeachingHoursResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.arcanic.dk/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> GetTeachingHoursResult;
    
    public GetTeachingHoursResponse()
    {
    }
    
    public GetTeachingHoursResponse(System.Nullable<int> GetTeachingHoursResult)
    {
        this.GetTeachingHoursResult = GetTeachingHoursResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface CourseSoapChannel : CourseSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class CourseSoapClient : System.ServiceModel.ClientBase<CourseSoap>, CourseSoap
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public CourseSoapClient(EndpointConfiguration endpointConfiguration) : 
            base(CourseSoapClient.GetBindingForEndpoint(endpointConfiguration), CourseSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CourseSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(CourseSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CourseSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(CourseSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public CourseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> CourseCatalogVersionsAsync()
    {
        return base.Channel.CourseCatalogVersionsAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetKeyValuesByVolumeAsync(string volume)
    {
        return base.Channel.GetKeyValuesByVolumeAsync(volume);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCatalogVersionSelectionAsync()
    {
        return base.Channel.GetCatalogVersionSelectionAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseByPassVolumeSettingsAsync(string courseCode, string yearGroup, System.Guid systemToken)
    {
        return base.Channel.GetCourseByPassVolumeSettingsAsync(courseCode, yearGroup, systemToken);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseAsync(string courseCode, string yearGroup)
    {
        return base.Channel.GetCourseAsync(courseCode, yearGroup);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseNewestPublicAsync(string CourseCode)
    {
        return base.Channel.GetCourseNewestPublicAsync(CourseCode);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseNewestBeforeVolumeAsync(string CourseCode, string Volume)
    {
        return base.Channel.GetCourseNewestBeforeVolumeAsync(CourseCode, Volume);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseResponsibleListAsync(string courseCode)
    {
        return base.Channel.GetCourseResponsibleListAsync(courseCode);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseTeachersListAsync(string courseCode)
    {
        return base.Channel.GetCourseTeachersListAsync(courseCode);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCourseTeachersAndSuperusersListAsync(string courseCode, bool includeSuperUsers)
    {
        return base.Channel.GetCourseTeachersAndSuperusersListAsync(courseCode, includeSuperUsers);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetLabelsAsync()
    {
        return base.Channel.GetLabelsAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> SearchDtuShb_FullAsync(string courseCode, string searchWords, string department, string teachingPeriod, string CourseCatalogVersion, string courseCodeStart, string teachingLanguage, string courseIDList, string resultType, string education, string CourseType, string MasterRegular, string openUniversity, string textStudieboksen)
    {
        return base.Channel.SearchDtuShb_FullAsync(courseCode, searchWords, department, teachingPeriod, CourseCatalogVersion, courseCodeStart, teachingLanguage, courseIDList, resultType, education, CourseType, MasterRegular, openUniversity, textStudieboksen);
    }
    
    public System.Threading.Tasks.Task<CourseTitleAndVolume[]> PublishedPickerAsync(string term, string volume, int maxResults)
    {
        return base.Channel.PublishedPickerAsync(term, volume, maxResults);
    }
    
    public System.Threading.Tasks.Task<CourseTitleAndVolume[]> DraftPickerAsync(string term, string volume, int maxResults, System.Guid systemToken)
    {
        return base.Channel.DraftPickerAsync(term, volume, maxResults, systemToken);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> SearchDtuShbByCourseCodeOrTitleAsync(string searchWords)
    {
        return base.Channel.SearchDtuShbByCourseCodeOrTitleAsync(searchWords);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseFromCourseIdAsync(int courseId)
    {
        return base.Channel.GetCourseFromCourseIdAsync(courseId);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsAsync()
    {
        return base.Channel.GetDepartmentsAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetStudieBoksAsync(string aargang, string lang)
    {
        return base.Channel.GetStudieBoksAsync(aargang, lang);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetHTMLDescriptionAsync(string CourseCode, string CourseCatalogVersion)
    {
        return base.Channel.GetHTMLDescriptionAsync(CourseCode, CourseCatalogVersion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetOpenCatalogVersionsAsync()
    {
        return base.Channel.GetOpenCatalogVersionsAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetTimeTableGroupAsync()
    {
        return base.Channel.GetTimeTableGroupAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsGivenCatalogAsync(string CourseCatalogVersion)
    {
        return base.Channel.GetDepartmentsGivenCatalogAsync(CourseCatalogVersion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetSearchValuesAsync()
    {
        return base.Channel.GetSearchValuesAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseCodeStartLettersAsync(string catalogVersion)
    {
        return base.Channel.GetCourseCodeStartLettersAsync(catalogVersion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByCourseCodeStartingLettersAsync(string letters, string catalogversion)
    {
        return base.Channel.GetCoursesByCourseCodeStartingLettersAsync(letters, catalogversion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByStartingLetterAsync(char letter, string userLang, string catalogversion)
    {
        return base.Channel.GetCoursesByStartingLetterAsync(letter, userLang, catalogversion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByDepartmentAsync(string department, string catalogversion)
    {
        return base.Channel.GetCoursesByDepartmentAsync(department, catalogversion);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCoursesByProgrammeLevelInPreferedVolumeAsync(string programmeLevel)
    {
        return base.Channel.GetCoursesByProgrammeLevelInPreferedVolumeAsync(programmeLevel);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetArchivedCoursesByVolumeAndDepartmentAsync(string volume, string department)
    {
        return base.Channel.GetArchivedCoursesByVolumeAndDepartmentAsync(volume, department);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseHoldingsAsync(string courseCode, string volume, string lang)
    {
        return base.Channel.GetCourseHoldingsAsync(courseCode, volume, lang);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseHoldingsByIdAsync(int courseId, string lang)
    {
        return base.Channel.GetCourseHoldingsByIdAsync(courseId, lang);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetFrontMessageAsync()
    {
        return base.Channel.GetFrontMessageAsync();
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseResponsiblesCoursesInOpenVolumesAsync(int cwis)
    {
        return base.Channel.GetCourseResponsiblesCoursesInOpenVolumesAsync(cwis);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetTeacherCoursesInCurrentAndPriorYearAsync(int cwis)
    {
        return base.Channel.GetTeacherCoursesInCurrentAndPriorYearAsync(cwis);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourselistForExamReportingAsync(string courseNumbers, string yearGroup, string departmentKey)
    {
        return base.Channel.GetCourselistForExamReportingAsync(courseNumbers, yearGroup, departmentKey);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetCourseResponsiblesCoursesInSpecificVolumeAsync(int cwis, string volume)
    {
        return base.Channel.GetCourseResponsiblesCoursesInSpecificVolumeAsync(cwis, volume);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDepartmentsResourcesInSpecificVolumeAsync(string volume)
    {
        return base.Channel.GetDepartmentsResourcesInSpecificVolumeAsync(volume);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForAUSReportAsync(string volume, string[] courseCodes)
    {
        return base.Channel.GetDataForAUSReportAsync(volume, courseCodes);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForStudyplanAsync(string volume, string[] courseCodes)
    {
        return base.Channel.GetDataForStudyplanAsync(volume, courseCodes);
    }
    
    public System.Threading.Tasks.Task<CourseTitle[]> GetCoursesTitlesAsync(string volume, string[] courseCodes)
    {
        return base.Channel.GetCoursesTitlesAsync(volume, courseCodes);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlElement> GetDataForGradeEntryAsync(string volume, string[] courseCodes)
    {
        return base.Channel.GetDataForGradeEntryAsync(volume, courseCodes);
    }
    
    public System.Threading.Tasks.Task<CourseExamPlanner[]> GetDataForExamPlannerAsync(string volume, string[] courseCodes)
    {
        return base.Channel.GetDataForExamPlannerAsync(volume, courseCodes);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetTeachingHoursResponse> CourseSoap.GetTeachingHoursAsync(GetTeachingHoursRequest request)
    {
        return base.Channel.GetTeachingHoursAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetTeachingHoursResponse> GetTeachingHoursAsync(string volume, string courseCode)
    {
        GetTeachingHoursRequest inValue = new GetTeachingHoursRequest();
        inValue.volume = volume;
        inValue.courseCode = courseCode;
        return ((CourseSoap)(this)).GetTeachingHoursAsync(inValue);
    }
    
    public System.Threading.Tasks.Task<string[]> GetCoursesWithDurationAsync(string volume, string duration)
    {
        return base.Channel.GetCoursesWithDurationAsync(volume, duration);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDataForEuroTeQAsync(string yearGroup, System.Guid systemId)
    {
        return base.Channel.GetDataForEuroTeQAsync(yearGroup, systemId);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CourseSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.CourseSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
            httpsBindingElement.AllowCookies = true;
            httpsBindingElement.MaxBufferSize = int.MaxValue;
            httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpsBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.CourseSoap))
        {
            return new System.ServiceModel.EndpointAddress("https://kurser.dtu.dk/coursewebservicev2/course.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.CourseSoap12))
        {
            return new System.ServiceModel.EndpointAddress("https://kurser.dtu.dk/coursewebservicev2/course.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        CourseSoap,
        
        CourseSoap12,
    }
}
