//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner.Backend.Soap.Volumes
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Volume", Namespace="http://schemas.datacontract.org/2004/07/VolumeService")]
    public partial class Volume : object
    {
        
        private bool ActiveField;
        
        private bool CurrentField;
        
        private bool EditableField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Current
        {
            get
            {
                return this.CurrentField;
            }
            set
            {
                this.CurrentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Editable
        {
            get
            {
                return this.EditableField;
            }
            set
            {
                this.EditableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Education", Namespace="http://schemas.datacontract.org/2004/07/VolumeService")]
    public partial class Education : object
    {
        
        private int IdField;
        
        private Planner.Backend.Soap.Volumes.Line[] LinesField;
        
        private Planner.Backend.Soap.Volumes.LanguageItem NameField;
        
        private System.Guid StaticGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Volumes.Line[] Lines
        {
            get
            {
                return this.LinesField;
            }
            set
            {
                this.LinesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Volumes.LanguageItem Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StaticGuid
        {
            get
            {
                return this.StaticGuidField;
            }
            set
            {
                this.StaticGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageItem", Namespace="http://schemas.datacontract.org/2004/07/VolumeService")]
    public partial class LanguageItem : object
    {
        
        private string DanishField;
        
        private string EnglishField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Danish
        {
            get
            {
                return this.DanishField;
            }
            set
            {
                this.DanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string English
        {
            get
            {
                return this.EnglishField;
            }
            set
            {
                this.EnglishField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Line", Namespace="http://schemas.datacontract.org/2004/07/VolumeService")]
    public partial class Line : object
    {
        
        private string CodeField;
        
        private bool IsInDanishField;
        
        private bool IsInEnglishField;
        
        private Planner.Backend.Soap.Volumes.LanguageItem NameField;
        
        private Planner.Backend.Soap.Volumes.LanguageItem PopularTitleField;
        
        private string ShortTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInDanish
        {
            get
            {
                return this.IsInDanishField;
            }
            set
            {
                this.IsInDanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInEnglish
        {
            get
            {
                return this.IsInEnglishField;
            }
            set
            {
                this.IsInEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Volumes.LanguageItem Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Volumes.LanguageItem PopularTitle
        {
            get
            {
                return this.PopularTitleField;
            }
            set
            {
                this.PopularTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortTitle
        {
            get
            {
                return this.ShortTitleField;
            }
            set
            {
                this.ShortTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralView", Namespace="http://schemas.datacontract.org/2004/07/VolumeService")]
    public partial class GeneralView : object
    {
        
        private string GuidField;
        
        private Planner.Backend.Soap.Volumes.LanguageItem NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Volumes.LanguageItem Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Planner.Backend.Soap.Volumes.IVolumeService")]
    public interface IVolumeService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolumeService/GetVolumes", ReplyAction="http://tempuri.org/IVolumeService/GetVolumesResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Volume[]> GetVolumesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolumeService/GetEducationsInVolume", ReplyAction="http://tempuri.org/IVolumeService/GetEducationsInVolumeResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Education[]> GetEducationsInVolumeAsync(int volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolumeService/GetEducationsInVolumeDraft", ReplyAction="http://tempuri.org/IVolumeService/GetEducationsInVolumeDraftResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Education[]> GetEducationsInVolumeDraftAsync(int volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVolumeService/GetGeneralViewsInVolume", ReplyAction="http://tempuri.org/IVolumeService/GetGeneralViewsInVolumeResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.GeneralView[]> GetGeneralViewsInVolumeAsync(int volume);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IVolumeServiceChannel : Planner.Backend.Soap.Volumes.IVolumeService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VolumeServiceClient : System.ServiceModel.ClientBase<Planner.Backend.Soap.Volumes.IVolumeService>, Planner.Backend.Soap.Volumes.IVolumeService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VolumeServiceClient() : 
                base(VolumeServiceClient.GetDefaultBinding(), VolumeServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVolumeService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VolumeServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VolumeServiceClient.GetBindingForEndpoint(endpointConfiguration), VolumeServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VolumeServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VolumeServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VolumeServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VolumeServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VolumeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Volume[]> GetVolumesAsync()
        {
            return base.Channel.GetVolumesAsync();
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Education[]> GetEducationsInVolumeAsync(int volume)
        {
            return base.Channel.GetEducationsInVolumeAsync(volume);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.Education[]> GetEducationsInVolumeDraftAsync(int volume)
        {
            return base.Channel.GetEducationsInVolumeDraftAsync(volume);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Volumes.GeneralView[]> GetGeneralViewsInVolumeAsync(int volume)
        {
            return base.Channel.GetGeneralViewsInVolumeAsync(volume);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVolumeService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVolumeService))
            {
                return new System.ServiceModel.EndpointAddress("https://sdb.dtu.dk/VolumeService/VolumeService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VolumeServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVolumeService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VolumeServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVolumeService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVolumeService,
        }
    }
}
