//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner.Backend.Soap.Courseblocks
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Courseblock", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class Courseblock : object
    {
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyleaderCourseAssociation", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class StudyleaderCourseAssociation : object
    {
        
        private string CourseCodeField;
        
        private int MatrikelIdField;
        
        private string StadsCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCode
        {
            get
            {
                return this.CourseCodeField;
            }
            set
            {
                this.CourseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatrikelId
        {
            get
            {
                return this.MatrikelIdField;
            }
            set
            {
                this.MatrikelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StadsCode
        {
            get
            {
                return this.StadsCodeField;
            }
            set
            {
                this.StadsCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudyBoxInfo", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class StudyBoxInfo : object
    {
        
        private string[] CourseCodesField;
        
        private string DanishField;
        
        private string EnglishField;
        
        private bool ShownField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CourseCodes
        {
            get
            {
                return this.CourseCodesField;
            }
            set
            {
                this.CourseCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Danish
        {
            get
            {
                return this.DanishField;
            }
            set
            {
                this.DanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string English
        {
            get
            {
                return this.EnglishField;
            }
            set
            {
                this.EnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Shown
        {
            get
            {
                return this.ShownField;
            }
            set
            {
                this.ShownField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirstTermCollection", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class FirstTermCollection : object
    {
        
        private Planner.Backend.Soap.Courseblocks.Course[] CoursesField;
        
        private int EducationIdField;
        
        private Planner.Backend.Soap.Courseblocks.CollectionMetadata MetadataField;
        
        private string TitleDanishField;
        
        private string TitleEnglishField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Courseblocks.Course[] Courses
        {
            get
            {
                return this.CoursesField;
            }
            set
            {
                this.CoursesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationId
        {
            get
            {
                return this.EducationIdField;
            }
            set
            {
                this.EducationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Courseblocks.CollectionMetadata Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleDanish
        {
            get
            {
                return this.TitleDanishField;
            }
            set
            {
                this.TitleDanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleEnglish
        {
            get
            {
                return this.TitleEnglishField;
            }
            set
            {
                this.TitleEnglishField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollectionMetadata", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class CollectionMetadata : object
    {
        
        private string PopularTitleDanishField;
        
        private string PopularTitleEnglishField;
        
        private string StadsCodeField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PopularTitleDanish
        {
            get
            {
                return this.PopularTitleDanishField;
            }
            set
            {
                this.PopularTitleDanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PopularTitleEnglish
        {
            get
            {
                return this.PopularTitleEnglishField;
            }
            set
            {
                this.PopularTitleEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StadsCode
        {
            get
            {
                return this.StadsCodeField;
            }
            set
            {
                this.StadsCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Studybase.CourseblockService")]
    public partial class Course : object
    {
        
        private string CourseCodeField;
        
        private string VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseCode
        {
            get
            {
                return this.CourseCodeField;
            }
            set
            {
                this.CourseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Planner.Backend.Soap.Courseblocks.ICourseblockService")]
    public interface ICourseblockService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetCourseblockNames", ReplyAction="http://tempuri.org/ICourseblockService/GetCourseblockNamesResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.Courseblock[]> GetCourseblockNamesAsync(string courseCode, int volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetCourseblocksInVolume", ReplyAction="http://tempuri.org/ICourseblockService/GetCourseblocksInVolumeResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.Courseblock[]> GetCourseblocksInVolumeAsync(int volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetCourseblock", ReplyAction="http://tempuri.org/ICourseblockService/GetCourseblockResponse")]
        System.Threading.Tasks.Task<string[]> GetCourseblockAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetStudyleaderCourseAssociations", ReplyAction="http://tempuri.org/ICourseblockService/GetStudyleaderCourseAssociationsResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyleaderCourseAssociation[]> GetStudyleaderCourseAssociationsAsync(int volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetStudyBoxInfoByVolumeAndCourseCodes", ReplyAction="http://tempuri.org/ICourseblockService/GetStudyBoxInfoByVolumeAndCourseCodesRespo" +
            "nse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyBoxInfo[]> GetStudyBoxInfoByVolumeAndCourseCodesAsync(int volume, string[] courseCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetStudyBoxInfoByVolumes", ReplyAction="http://tempuri.org/ICourseblockService/GetStudyBoxInfoByVolumesResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyBoxInfo[]> GetStudyBoxInfoByVolumesAsync(int[] volumes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseblockService/GetFirstTermCourses", ReplyAction="http://tempuri.org/ICourseblockService/GetFirstTermCoursesResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.FirstTermCollection[]> GetFirstTermCoursesAsync(int volume, System.Nullable<int> educationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICourseblockServiceChannel : Planner.Backend.Soap.Courseblocks.ICourseblockService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CourseblockServiceClient : System.ServiceModel.ClientBase<Planner.Backend.Soap.Courseblocks.ICourseblockService>, Planner.Backend.Soap.Courseblocks.ICourseblockService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CourseblockServiceClient() : 
                base(CourseblockServiceClient.GetDefaultBinding(), CourseblockServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICourseblockService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseblockServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CourseblockServiceClient.GetBindingForEndpoint(endpointConfiguration), CourseblockServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseblockServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CourseblockServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseblockServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CourseblockServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseblockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.Courseblock[]> GetCourseblockNamesAsync(string courseCode, int volume)
        {
            return base.Channel.GetCourseblockNamesAsync(courseCode, volume);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.Courseblock[]> GetCourseblocksInVolumeAsync(int volume)
        {
            return base.Channel.GetCourseblocksInVolumeAsync(volume);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCourseblockAsync(int id)
        {
            return base.Channel.GetCourseblockAsync(id);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyleaderCourseAssociation[]> GetStudyleaderCourseAssociationsAsync(int volume)
        {
            return base.Channel.GetStudyleaderCourseAssociationsAsync(volume);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyBoxInfo[]> GetStudyBoxInfoByVolumeAndCourseCodesAsync(int volume, string[] courseCodes)
        {
            return base.Channel.GetStudyBoxInfoByVolumeAndCourseCodesAsync(volume, courseCodes);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.StudyBoxInfo[]> GetStudyBoxInfoByVolumesAsync(int[] volumes)
        {
            return base.Channel.GetStudyBoxInfoByVolumesAsync(volumes);
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Courseblocks.FirstTermCollection[]> GetFirstTermCoursesAsync(int volume, System.Nullable<int> educationId)
        {
            return base.Channel.GetFirstTermCoursesAsync(volume, educationId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICourseblockService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICourseblockService))
            {
                return new System.ServiceModel.EndpointAddress("https://sdb.dtu.dk/CourseBlokService/CourseblockService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CourseblockServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICourseblockService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CourseblockServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICourseblockService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICourseblockService,
        }
    }
}
