//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planner.Backend.Soap.Visualizations
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visualization", Namespace="http://schemas.datacontract.org/2004/07/Studybase.VisualizationService")]
    public partial class Visualization : object
    {
        
        private System.Guid GuidField;
        
        private int IdField;
        
        private Planner.Backend.Soap.Visualizations.LanguageItem NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Planner.Backend.Soap.Visualizations.LanguageItem Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LanguageItem", Namespace="http://schemas.datacontract.org/2004/07/Studybase.VisualizationService")]
    public partial class LanguageItem : object
    {
        
        private string DanishField;
        
        private string EnglishField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Danish
        {
            get
            {
                return this.DanishField;
            }
            set
            {
                this.DanishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string English
        {
            get
            {
                return this.EnglishField;
            }
            set
            {
                this.EnglishField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Planner.Backend.Soap.Visualizations.IVisualizationService")]
    public interface IVisualizationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizationService/GetVisualizationsInEducation", ReplyAction="http://tempuri.org/IVisualizationService/GetVisualizationsInEducationResponse")]
        System.Threading.Tasks.Task<Planner.Backend.Soap.Visualizations.Visualization[]> GetVisualizationsInEducationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizationService/GetVisualization", ReplyAction="http://tempuri.org/IVisualizationService/GetVisualizationResponse")]
        System.Threading.Tasks.Task<string> GetVisualizationAsync(int visualizationId, string code, int volume, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizationService/GetVisualizationByGuid", ReplyAction="http://tempuri.org/IVisualizationService/GetVisualizationByGuidResponse")]
        System.Threading.Tasks.Task<string> GetVisualizationByGuidAsync(System.Guid visualizationGuid, string code, int volume, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizationService/GetVisualizationDraft", ReplyAction="http://tempuri.org/IVisualizationService/GetVisualizationDraftResponse")]
        System.Threading.Tasks.Task<string> GetVisualizationDraftAsync(int visualizationId, string code, int volume, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisualizationService/GetGeneralVisualization", ReplyAction="http://tempuri.org/IVisualizationService/GetGeneralVisualizationResponse")]
        System.Threading.Tasks.Task<string> GetGeneralVisualizationAsync(string visualizationGuid, int volume, string language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IVisualizationServiceChannel : Planner.Backend.Soap.Visualizations.IVisualizationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VisualizationServiceClient : System.ServiceModel.ClientBase<Planner.Backend.Soap.Visualizations.IVisualizationService>, Planner.Backend.Soap.Visualizations.IVisualizationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VisualizationServiceClient() : 
                base(VisualizationServiceClient.GetDefaultBinding(), VisualizationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVisualizationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisualizationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VisualizationServiceClient.GetBindingForEndpoint(endpointConfiguration), VisualizationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisualizationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VisualizationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisualizationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VisualizationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisualizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Planner.Backend.Soap.Visualizations.Visualization[]> GetVisualizationsInEducationAsync(int id)
        {
            return base.Channel.GetVisualizationsInEducationAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> GetVisualizationAsync(int visualizationId, string code, int volume, string language)
        {
            return base.Channel.GetVisualizationAsync(visualizationId, code, volume, language);
        }
        
        public System.Threading.Tasks.Task<string> GetVisualizationByGuidAsync(System.Guid visualizationGuid, string code, int volume, string language)
        {
            return base.Channel.GetVisualizationByGuidAsync(visualizationGuid, code, volume, language);
        }
        
        public System.Threading.Tasks.Task<string> GetVisualizationDraftAsync(int visualizationId, string code, int volume, string language)
        {
            return base.Channel.GetVisualizationDraftAsync(visualizationId, code, volume, language);
        }
        
        public System.Threading.Tasks.Task<string> GetGeneralVisualizationAsync(string visualizationGuid, int volume, string language)
        {
            return base.Channel.GetGeneralVisualizationAsync(visualizationGuid, volume, language);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVisualizationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVisualizationService))
            {
                return new System.ServiceModel.EndpointAddress("https://sdb.dtu.dk/VisualizationService/VisualizationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VisualizationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVisualizationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VisualizationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVisualizationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVisualizationService,
        }
    }
}
